result_dir: result
features_dir: features
luigi_dir: luigi
experiment_path: experiment.json
target_col: y
evaluator_flag: rmse
feature_importance_model_flag: lgbm_rmse
num_class: 8
importance_flag: mean # mean, null_importance
null_importance_trials: 10
trainer_flag: basic # basic, down_sample_bagging
folds_generator_flag: kfold # kfold, group, stratified, stratified_group
group_kfolds_col: gameID # atbat_id, gameID
verbose_eval: 100
num_boost_round: 2000
early_stopping_rounds: 20
fold_num: 5
seed: 42
bagging_num: 5
base_class: 3 # downsampling target base class (int)
allow_less_than_base: True
drop_cols:
   - pitchType